site_name: web前端开发
site_author: "zhousir"
site_description: "web前端开发wiki"
site_url: "https://www.yuguoxy.com/"
copyright: "Copyright © 2020 雨果学院wiki"

# curl 'jaspervdj.be/lorem-markdownum/markdown.txt' > docs/about.md
# curl 'jaspervdj.be/lorem-markdownum/markdown.txt' > docs/development.md
# 源码地址
#repo_name: '雨果在线'
#repo_url: 'http://yuguoxy.cn'

# 本地调试端口
# dev_addr: 192.168.0.101:4050

nav:
  - 介绍:
      - 1. 课程介绍: index.md
  - vue框架:
      - 1. vue简介: vue/vue简介.md
      - 2. vue安装: vue/vue安装.md
  - web技术:
      - 1. web安全: web/Web安全.md
      - 2. 无限下拉方案: web/无限下拉方案.md
      - 3. css变量教程: web/css变量教程.md
  - api接口文档:
      - 1. 后台中心api文档: api/usermanger_api.md

theme:
  name: material # mkdocs readthedocs
  features:
    - tabs # 显示顶部导航栏
  palette: # 颜色
    primary: Blue Grey # 主色
    accent: Pink # 辅助色
  font: # 字体
    text: Ubuntu # 正文，默认为Roboto
    code: Ubuntu Mono # 代码，默认为Roboto Mono
  #favicon: /img/test_icon.png # 网页图标
  #logo: /img/test_icon.png # 顶端图标
  language: zh # 语言，默认为en

extra:
  search:
    language: "jp"

markdown_extensions:
  - admonition # 提示块
  - footnotes # 脚注
  - meta # 定义元数据，通过文章上下文控制，如disqus
  - pymdownx.caret # 下划线上标
  - pymdownx.tilde # 删除线下标
  - pymdownx.critic # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details # 提示块可折叠
  - pymdownx.inlinehilite # 行内代码高亮
  - pymdownx.mark # 文本高亮
  - pymdownx.smartsymbols # 符号转换
  - pymdownx.superfences # 代码嵌套在列表里
  - codehilite: # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - toc: # 锚点
      permalink: true
  #  - pymdownx.arithmatex  # 数学公式
  - pymdownx.betterem: # 对加粗和斜体更好的检测
      smart_enable: all
  #  - pymdownx.emoji:  # 表情
  #      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - pymdownx.magiclink  # 自动识别超链接
  - pymdownx.tasklist: # 复选框checklist
      custom_checkbox: true

# PDF导出插件
plugins:
  - search
#  - pdf-export #这个插件还有点问题，没有更新
